import type { Metadata } from "next";
import { Open_Sans } from "next/font/google"; // Import Open Sans from Google Fonts
import "./globals.css";

// Load Open Sans font with various weights
const openSans = Open_Sans({
  weight: ["300", "400", "600", "700", "800"], // Different font weights you want to use
  subsets: ["latin"], // You can specify other subsets if needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} antialiased`}>{children}</body>
    </html>
  );
}
